# Concept
predict how much revenue a given video idea will produce for tiger fitness. we also want to predict views, percent viewed, and change in subscribers

## Features (input 1-7, output 8-14)
1. video duration (bucketed, analytics based)
2. title polarity
3. title length (characters)
4. n links in description
5. category of video (vlog, training, nutrition, personal story, supplements and steroids)
6. product price range (bucketed, intuition based)
7. product type (apparel(3), supplements(2), food(1), coaching(4), nothing(0))
8. transactions
9. views
10. subs
11. average percent viewed
12. likes
13. Impressions
14. Impression click through

## Models
1. revenue prediction (predict sales volume, multiply by price range to give a revenue range)
2. views prediction
3. change in subscribers prediction
4. average percent viewed prediction
5. likes prediction

Data Sources...

manual entry or unsupervised learning: 5

youtube analytics report - video analytics overview: 2, 3, 9, 10, 11, 12

youtube analytics report - video analytics engadgement: 8, 13, 14

## Import statements

In [2]:
import pandas as pd

In [6]:
df = pd.read_csv(r'C:\Users\aacjp\Spencer\KPI_Analysis\Youtube.csv').drop(['Unnamed: 0'], axis='columns')
df.head()

,Video,Video title,Video publish time,Likes,Subscribers gained,Views,Average view duration,Average percentage viewed (%),Impressions,Impressions click-through rate (%),description,nlinks,title length,title polarity,Video duration,duration bucket
0,Ewdr2H2qmVY,ux of 4 produced by cashmoneyap,"Oct 7, 2018",8,3,182,73,31.63,810,8.52,19 shot by @gwen.holley and @its_jeremiahpr...,0,31,0.000000,230,0
1,ApXSnKR8lQU,retarded genius produced by letzer,"Nov 4, 2018",7,1,183,64,33.02,1251,8.63,3 shot by @gwen.holleyfollow me on instagra...,1,34,-0.800000,193,0
2,Hde5iY6CG8s,i tried to move to la,"Oct 1, 2019",4,0,52,279,35.42,188,11.70,9 This is by far the craziest thing I've ev...,0,21,0.000000,787,3
3,QVYOgNfa1Mk,your first machine learning model and beginner...,"Jun 13, 2021",2,3,82,140,8.94,62,4.84,20 Click Here for to book FREE Tutoring ses...,1,79,0.250000,1565,3
4,f-4wjPBSROo,smart kids equals hamster brain,"Jun 27, 2019",2,0,14,113,30.67,165,6.06,"16 Enjoy the videos and music you love, upl...",0,32,0.214286,368,1